blogDog/web/auth.py
# -*- coding: utf-8 -*-
# @Time : 2020/10/1
# @Author : Benny Jane
# @Email : 暂无
# @File : blog.py
# @Project : flask-blog-v1

from flask import render_template, redirect, url_for, Blueprint, flash
from flask_login import current_user, login_user, logout_user

from blogDog import Admin
from blogDog.common.utils import redirect_back
from blogDog.forms import LoginForm

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.first()
        if admin:
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)
                flash('A Dog， 欢迎登陆', 'info')
                return redirect_back()
            flash('Invalid username or password.', 'warning')
        else:
            flash('No account.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect_back()

blogDog/templates/_adminNav.html
<!-- 文章缩写框 -->
{% if current_user.is_authenticated %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
           aria-haspopup="true"
           aria-expanded="false">新增</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">文章</a>
            <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">分类</a>
            <a class="dropdown-item" href="{{ url_for('admin.new_link') }}">Task</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
           aria-haspopup="true"
           aria-expanded="false">管理</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('admin.manager_post') }}">文章</a>
            <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">分类</a>
            <a class="dropdown-item" href="{{ url_for('admin.manage_comment') }}">评论</a>
            <a class="dropdown-item" href="{{ url_for('admin.manage_link') }}">Task</a>
        </div>
    </li>
{% endif %}

blogDog/templates/_backToTop.html
<!-- 返回顶部 -->
<div id="backTop" style="position: fixed; right: 120px; bottom: 10vh; display: none">
    <span class="float-lg-right"><a href="#top"><img src="{{ url_for('static', filename='images/backToTop.png') }}"
                                                     style="width: 60px"> </a></span>
</div>

blogDog/templates/_errorInfo.html
{% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
{% endfor %}

blogDog/templates/_loginAndLogout.html
<!-- 登录页面的页脚 -->
<p class="float-right">
    <small>
        <!-- flask_login 中提供的全局变量 -->
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
        {% else %}
            <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
        {% endif %}
    </small>
</p>

blogDog/templates/_otherNav.html
{% from 'bootstrap/nav.html'  import render_nav_item %}
{% block extensionNav %}
{#    {{ render_nav_item('visual.index', 'Visual') }}#}
    {{ render_nav_item('task.index', 'TASKS') }}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
           aria-haspopup="true"
           aria-expanded="false">Themes</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('blog.change_theme', theme_name='Lux') }}">Lux</a>
            <a class="dropdown-item" href="{{ url_for('blog.change_theme', theme_name='Sketchy') }}">Sketchy</a>
            <a class="dropdown-item" href="{{ url_for('blog.change_theme', theme_name='Litera') }}">Litera</a>
            <a class="dropdown-item" href="{{ url_for('blog.change_theme', theme_name='Sandstone') }}">Sandstone</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('blog.change_codeStyle', code_style='agate') }}">agate</a>
            <a class="dropdown-item" href="{{ url_for('blog.change_codeStyle', code_style='dark') }}">dark</a>
            <a class="dropdown-item" href="{{ url_for('blog.change_codeStyle', code_style='zenburn') }}">zenburn</a>

        </div>
    </li>
{% endblock %}

blogDog/templates/_page.html
<div>
    <ul class="pagination">
        {% if page_params %}
            {% if page_params.total !=0 %}
                {% if page_params.is_prev ==1 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ page_params.url }}&page=1">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&laquo;</a>
                    </li>
                {% endif %}

                {% for idx in page_params.range %}
                    {% if idx == page_params.current %}
                        <li class="page-item active">
                            <a class="page-link" href="javascript:void(0);">{{ idx }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ page_params.url }}&page={{ idx }}">{{ idx }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_params.is_next ==1 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ page_params.url }}&page={{ page_params.total_pages }}">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&raquo;</a>
                    </li>
                {% endif %}
            {% endif %}

        {% else %}
            <!-- 数量为0 -->
        {% endif %}

    </ul>
</div>

blogDog/templates/base-backup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Benny Jane Of Blog</title>
    <link rel="icon" href="../static/favicon.ico">
    <link rel="stylesheet" href="../static/css/Lux.min.css" type="text/css">
    <link rel="stylesheet" href="../static/css/style.css" type="text/css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container col-md-8">
    <div style="display: flex; align-items: flex-start">
        <div class="col-md-9">
            <!-- 推荐文章，横向轮播图 -->
            <div class="alert alert-dismissible alert-warning" style="width: 100%; padding-right: 1.25rem">
                <div style="display: flex; justify-content: space-between">
                    <h4 class="alert-heading">Recommend!</h4>
                    <a type="button" class="btn" data-toggle="tooltip" data-placement="left" title=""
                            data-original-title="隐藏右侧边框" style="background-color: transparent; padding: 0 0">>>
                    </a>
                </div>
                <p class="mb-0">Best check yo self, you're not looking too good. Nulla vitae elit libero, a pharetra
                    augue.
                    Praesent commodo cursus magna, <a href="#" class="alert-link">vel scelerisque nisl consectetur
                        et</a>.
                </p>
            </div>

            <!-- 文章缩写框 -->
            <div class="card text-white bg-dark mb-3" style="width: 100%">
                <div class="card-body">
                    <a href="#"><h4 class="card-title" style="color: white"> Py-描述符的使用</h4></a>
                    <p class="card-text" style="color: #919aa1 !important">这是一篇原创的文章！Tree summer sister generation
                        president senior score. Fund service imagine
                        everybody toward again serve. Test particular kitchen TV foot daughter marriage he. </p>
                    <div style="display: flex;justify-content: space-between" class="text-right">
                        <span>
                            <a href="#"><span class="badge badge-success " style="font-weight: normal">python</span></a>
                            <a href="#"><span class="badge badge-success"
                                              style="font-weight: normal;">advance</span></a>
                        </span>
                        <span>
                            <a href="#"><span class="badge badge-light"
                                              style="color: #919aa1 !important; background-color: transparent">2020-09-30 10:29:30</span></a>
                        </span>
                    </div>
                </div>
            </div>
            <!-- 文章缩写框 -->
            <div class="card text-white bg-dark mb-3" style="width: 100%">
                <div class="card-body">
                    <a href="#"><h4 class="card-title" style="color: white"> Py-装饰器的用法</h4></a>
                    <p class="card-text" style="color: #919aa1 !important">这是一篇原创的文章！Tree summer sister generation
                        president senior score. Fund service imagine
                        everybody toward again serve. Test particular kitchen TV foot daughter marriage he. Case those
                        international common both later involve. Relate million ahead ten. About for... </p>
                    <div style="display: flex;justify-content: space-between" class="text-right">
                        <span>
                            <a href="#"><span class="badge badge-success " style="font-weight: normal">python</span></a>
                            <a href="#"><span class="badge badge-success"
                                              style="font-weight: normal;">advance</span></a>
                        </span>
                        <span>
                            <a href="#"><span class="badge badge-light"
                                              style="color: #919aa1 !important; background-color: transparent">2020-09-30 10:29:30</span></a>
                        </span>
                    </div>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3" style="width: 100%">
                <div class="card-body">
                    <a href="#"><h4 class="card-title" style="color: white"> GO-基本项目结构</h4></a>
                    <p class="card-text" style="color: #919aa1 !important">这是一篇原创的文章！Tree summer sister generation
                        president senior score. Fund service imagine
                        everybody toward again serve. Test particular kitchen TV foot daughter marriage he. Case those
                        international common both later involve. Relate million ahead ten. About for... </p>
                    <div style="display: flex;justify-content: space-between">
                        <span>
                            <a href="#"><span class="badge badge-success" style="font-weight: normal">goland</span></a>
                            <a href="#"><span class="badge badge-success" style="font-weight: normal">base</span></a>
                        </span>
                        <span style="right: 0px">
                            <a href="#"><span class="badge badge-light"
                                              style="color: #919aa1 !important; background-color: transparent">2020-09-30</span></a>
                        </span>
                    </div>


                </div>
            </div>

            <!-- 页码 -->
            <div>
                <ul class="pagination">
                    <li class="page-item disabled">
                        <a class="page-link" href="#">&laquo;</a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="#">1</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">2</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">4</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">5</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- 右侧内容框 -->
        <div class="col-md-3" id="content-right-card">
            <div class="card mb-3">
                <h3 class="card-header">Dogville</h3>
                <div class="card-body">
                    <h5 class="card-title">你看，那个人好像一条狗.</h5>
                    <h6 class="card-subtitle text-muted">Support card subtitle</h6>
                </div>
                <img style="height: 200px; width: 100%; display: block;"
                     src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22318%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20318%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_158bd1d28ef%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A16pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_158bd1d28ef%22%3E%3Crect%20width%3D%22318%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22129.359375%22%20y%3D%2297.35%22%3EImage%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                     alt="Card image">
                <!-- 文章分类统计 -->
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center">Cras justo odio
                        <span class="badge badge-primary badge-pill">14</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Cras justo odio
                        <span class="badge badge-primary badge-pill">14</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Dapibus ac facilisis in
                        <span class="badge badge-primary badge-pill">2</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Morbi leo risus
                        <span class="badge badge-primary badge-pill">1</span>
                    </li>
                </ul>

            </div>
            <div class="card " style="margin-bottom: 1rem !important;">
                <div class="card-body">
                    <h4 class="card-title">Flask专题文章</h4>
                    <h6 class="card-subtitle mb-2 text-muted">当前已完成20篇</h6>
                    <p class="card-text">Flask入门知识点详解，记录代码细节，该专题仍在完善中...</p>
                    <a href="#" class="card-link">查看所有文章</a>
                </div>
            </div>
            <div class="card list-group-flush" style="margin-bottom: 1rem !important;">
                <div class="card-body">
                    <h4 class="card-title">Go项目专题</h4>
                    <h6 class="card-subtitle mb-2 text-muted">当前已完成20篇</h6>
                    <p class="card-text">第一个Go项目记录...</p>
                    <a href="#" class="card-link">查看所有文章</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 页脚 -->
<div class="container col-md-8">
    <footer style="width: 100%">
        <p class="float-left">
            <small> &copy; 2020 <a href="http://greyli.com" title="Written by Grey Li">Benny Jane</a> -
                <a href="https://github.com/greyli/bluelog" title="Fork me on GitHub">GitHub</a> -
                <a href="http://helloflask.com" title="A HelloFlask project">My Blog</a>
            </small>
        </p>
        <p class="float-right">
            <small>
                <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
            </small>
        </p>
    </footer>
</div>


<script type="text/javascript" src="../static/js/jquery-3.2.1.slim.min.js"></script>
<script type="text/javascript" src="../static/js/popper.min.js"></script>
<script type="text/javascript" src="../static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../static/js/script.js"></script>
<script type="text/javascript" src="../static/js/moment-with-locales.min.js"></script>
</body>
</html>

blogDog/templates/base.html
{% from 'bootstrap/nav.html'  import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-f">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %} {% endblock title %} - {{ admin.blog_title|default('Blog Title') }}</title>
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'Lux')) }}"
              type="text/css">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock head %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="padding: 0.6rem 2rem;">
        <a class="navbar-brand" href="{{ url_for('blog.index') }}">PyGoRun</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                {{ render_nav_item('blog.index', 'Home') }}
                {% include '_otherNav.html' %}
                {% include '_adminNav.html' %}
            </ul>
            <form class="form-inline my-2 my-lg-0" method="post" action="{{ url_for('blog.search_post') }}">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" style="">搜索</button>
            </form>
        </div>
    </nav>
{% endblock nav %}


<!-- 添加背景图效果
<div class="bg-fog">
{#{{ url_for('static', filename='images/bg/bg11.jpg') }}#}
    <div class="index-bg" style="background-image:url('')">
    </div>
</div>
-->

{% block mainBody %}
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}

    <script type="text/javascript">
        window.onload = function () {
            var obtn = document.getElementById('backTop');
            //获取页面可视区的高度
            var clientHeight = document.documentElement.clientHeight;
            var timer = null;
            var isTop = true;
            window.onscroll = function () {
                var osTop = document.documentElement.scrollTop || document.body.scrollTop;
                if (osTop >= clientHeight) {
                    //显示按钮
                    obtn.style.display = 'block';
                } else {
                    //隐藏按钮
                    obtn.style.display = 'none';
                }
                if (!isTop) {
                    clearInterval(timer);
                }
                isTop = false;
            };
            obtn.onclick = function () {
                //设置定时器
                timer = setInterval(function () {
                    //获取滚动条距离顶部的高度
                    var osTop = document.documentElement.scrollTop || document.body.scrollTop;
                    var ispeed = Math.floor(-osTop / 6);
                    document.documentElement.scrollTop = document.body.scrollTop = osTop + ispeed;

                    isTop = true;
                    if (osTop === 0) {
                        clearInterval(timer);
                    }
                }, 30);
            };
        };
    </script>
{% endblock %}
</body>
</html>